"""
§3 · 05 — Multimodal input: images and PDFs.

    uv run section_3_bedrock/05_multimodal.py                  # image + PDF
    uv run section_3_bedrock/05_multimodal.py path/to/photo.jpg
    uv run section_3_bedrock/05_multimodal.py path/to/file.pdf

A multimodal message is just a `content` list instead of a plain string:
one block of type "image" (base64-encoded bytes + a media type) and one
block of type "text" (the question). Claude reads both blocks together —
it isn't "shown an image then told a prompt", it sees them as one turn.

A PDF has no such block type, so there are two ways to send one, and this
file runs both against the same document:

    PART 2  render each page to a PNG, send N image blocks   (invoke_model)
    PART 3  send the PDF bytes in a `document` block         (converse)

Rendering works with any vision model and shows the model exactly what a
human sees — stamps, handwriting, ticked boxes, table rules. The document
block needs no rendering step, no DPI decision and no PDF library.

What it does NOT reliably buy is tokens. For Claude on Bedrock the document
block is also converted to page images upstream, so on this two-page form the
two paths land within ~10% of each other. Part 3 prints both counts rather
than asserting a winner — measure it on YOUR documents.

If no path is given it uses the sample photo in images/ and the sample form
in sample_docs/, so the file runs standalone.
"""

import base64
import json
import mimetypes
import sys
from pathlib import Path

import _bootstrap  # noqa: F401

from _common import MODEL_ID, bedrock_runtime

# ---------------------------------------------------------------- samples


SAMPLE_IMAGE_PATH = Path(__file__).parent / "images/images.jpeg"
SAMPLE_PDF_PATH = Path(__file__).resolve().parent.parent / "sample_docs/expenses.pdf"

# Rendering resolution for PART 2. Bedrock downscales anything past ~1568px on
# the long edge, so on A4 the token count stops rising above roughly 150 —
# past that you upload more bytes for the same tokens and the same accuracy.
DPI = 150

# Bedrock only accepts these four for Claude's "image" content block.
SUPPORTED_MEDIA_TYPES = {"image/jpeg", "image/png", "image/gif", "image/webp"}


def ensure_sample_image() -> Path:
    """The bundled sample photo, used when no path is given on the command line."""
    if not SAMPLE_IMAGE_PATH.exists():
        raise SystemExit(
            f"No sample image at {SAMPLE_IMAGE_PATH}.\n"
            "  Pass your own instead:\n"
            "    uv run section_3_bedrock/05_multimodal.py path/to/photo.jpg"
        )
    return SAMPLE_IMAGE_PATH


def ensure_sample_pdf() -> Path:
    """The bundled sample expense form, generated by make_sample_pdf.py."""
    if not SAMPLE_PDF_PATH.exists():
        raise SystemExit(
            f"No sample PDF at {SAMPLE_PDF_PATH}.\n"
            "  Generate it:  uv run make_sample_pdf.py\n"
            "  Or pass your own:\n"
            "    uv run section_3_bedrock/05_multimodal.py path/to/file.pdf"
        )
    return SAMPLE_PDF_PATH


# ---------------------------------------------------------------- the block

def image_block(path: Path) -> dict:
    """Turns a local image file into a Claude "image" content block."""
    media_type, _ = mimetypes.guess_type(path.name)
    if media_type not in SUPPORTED_MEDIA_TYPES:
        raise ValueError(
            f"unsupported media type {media_type!r} for {path.name}; "
            f"use one of {sorted(SUPPORTED_MEDIA_TYPES)}"
        )

    data = base64.b64encode(path.read_bytes()).decode("utf-8")
    return {
        "type": "image",
        "source": {
            "type": "base64",
            "media_type": media_type,
            "data": data,
        },
    }


def pdf_page_blocks(pdf: Path, dpi: int = DPI) -> list[dict]:
    """Render every page of a PDF to PNG and wrap each as an "image" block.

    The whole pipeline is three lines per page: page -> bitmap -> base64. The
    model never receives the PDF; it receives N pictures, exactly as a person
    scanning the printout would see them. That is why this path survives
    scans, stamps, handwriting and ticked checkboxes, and why it costs what a
    picture costs rather than what the text costs.

    PyMuPDF here rather than pdf2image: pdf2image shells out to poppler's
    pdftoppm, so `pip install` alone is not enough. PyMuPDF ships a
    self-contained wheel. The blocks are byte-identical either way.
    """
    try:
        import fitz  # PyMuPDF
    except ImportError:
        raise SystemExit(
            "PyMuPDF is not installed. It lives in the take-home extra:\n"
            "    uv sync --extra takehome"
        )

    blocks = []
    with fitz.open(pdf) as doc:
        for page in doc:
            png = page.get_pixmap(dpi=dpi).tobytes("png")
            blocks.append({
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": "image/png",
                    "data": base64.b64encode(png).decode("utf-8"),
                },
            })
    return blocks


# ---------------------------------------------------------------- binding

def ask(client, blocks: list[dict], question: str) -> dict:
    """One invoke_model call carrying N content blocks plus the question.

    Put the question AFTER the material it refers to. Models attend better
    that way, and it costs nothing to order it correctly.
    """
    body = json.dumps({
        "anthropic_version": "bedrock-2023-05-31",
        "messages": [{
            "role": "user",
            "content": blocks + [{"type": "text", "text": question}],
        }],
        "max_tokens": 1000,
    })
    return json.loads(
        client.invoke_model(modelId=MODEL_ID, body=body)["body"].read())


def ask_document(client, pdf: Path, question: str) -> dict:
    """Send the PDF ITSELF, with no rendering step, via the Converse API.

    Converse has a `document` block that invoke_model's Anthropic body does
    not: raw bytes plus a format, and Bedrock handles the rest. No PyMuPDF, no
    DPI to choose, no rendering code to maintain.

    The catch is that you no longer control what the model sees, and you cannot
    inspect it either — when an extraction goes wrong you have no rendered page
    to look at. Part 2 costs you a dependency and buys you that.

    Note it is not automatically the cheap option: for Claude the document is
    converted to page images upstream anyway. Part 3 prints both counts.

    `name` must be alphanumerics, spaces, hyphens, brackets and parentheses
    only — no dots. A filename passed through unchanged is a validation error.
    """
    return client.converse(
        modelId=MODEL_ID,
        messages=[{
            "role": "user",
            "content": [
                {"document": {
                    "format": "pdf",
                    "name": pdf.stem.replace("_", "-"),
                    "source": {"bytes": pdf.read_bytes()},
                }},
                {"text": question},
            ],
        }],
        inferenceConfig={"maxTokens": 1000},
    )


def show(envelope: dict) -> None:
    """Print the reply from an invoke_model envelope."""
    print(f"  stop_reason : {envelope['stop_reason']}")
    usage = envelope.get("usage", {})
    print(f"  tokens      : input={usage.get('input_tokens')} "
          f"output={usage.get('output_tokens')}")
    for block in envelope["content"]:
        if block["type"] == "text":
            print(f"  text        : {block['text'].strip()}")


def show_converse(response: dict) -> None:
    """Print the reply from a converse response. Different keys, same content."""
    usage = response["usage"]
    print(f"  stop_reason : {response['stopReason']}")
    print(f"  tokens      : input={usage['inputTokens']} output={usage['outputTokens']}")
    for block in response["output"]["message"]["content"]:
        if "text" in block:
            print(f"  text        : {block['text'].strip()}")


def banner(title: str) -> None:
    print(f"\n{'=' * 72}\n{title}\n{'=' * 72}")


# ---------------------------------------------------------------- parts

def part_1_image(client, image_path: Path) -> None:
    banner("1 · AN IMAGE — one image block plus one text block")
    print(f"  file        : {image_path}")
    show(ask(client, [image_block(image_path)],
             "What's in this image? Answer in one sentence."))


def part_2_pdf_as_images(client, pdf: Path) -> int:
    """Render the pages, ask a question, return the input token count."""
    banner(f"2 · A PDF AS IMAGES — rendered at {DPI} DPI")
    print(f"  file        : {pdf}")

    blocks = pdf_page_blocks(pdf)
    for i, b in enumerate(blocks, 1):
        kb = len(b["source"]["data"]) * 3 // 4 // 1024
        print(f"  page {i}      : ~{kb} KB of base64 PNG")

    envelope = ask(client, blocks,
                   "Read this form. Who is claiming, for what period, and what "
                   "do the line items add up to? Three short lines.")
    show(envelope)
    return envelope.get("usage", {}).get("input_tokens", 0)


def part_3_pdf_as_document(client, pdf: Path, rendered_tokens: int) -> None:
    banner("3 · THE SAME PDF AS A DOCUMENT — no rendering")
    print(f"  file        : {pdf}  ({pdf.stat().st_size // 1024} KB on disk)")

    response = ask_document(client, pdf,
                            "Read this form. Who is claiming, for what period, and "
                            "what do the line items add up to? Three short lines.")
    show_converse(response)

    native = response["usage"]["inputTokens"]
    print(f"\n  rendered    : {rendered_tokens} input tokens  (part 2, {DPI} DPI)")
    print(f"  document    : {native} input tokens  (part 3)")
    if native and rendered_tokens:
        cheaper = "rendered" if rendered_tokens < native else "document"
        diff = abs(rendered_tokens - native) / max(rendered_tokens, native)
        print(f"  cheaper     : {cheaper}, by {diff:.0%}")


def part_4_structured(client, pdf: Path) -> None:
    """Same pages, but the answer has to be JSON your code can use."""
    banner("4 · STRUCTURED OUTPUT — a PDF into a dict")

    schema = {
        "claimant": "string or null",
        "period": "string or null",
        "lines": [{"date": "DD/MM/YY", "description": "string", "amount": "number"}],
        "total_amount": "number, computed if not printed",
        "cost_centre": "string or null — null if genuinely absent, do not invent",
    }

    envelope = ask(
        client, pdf_page_blocks(pdf),
        "Extract this form as JSON matching this shape, and reply with the "
        f"JSON only, no prose:\n{json.dumps(schema, indent=2)}")

    raw = next(b["text"] for b in envelope["content"] if b["type"] == "text")
    data = json.loads(raw[raw.find("{"):raw.rfind("}") + 1])

    print(f"  claimant    : {data.get('claimant')}")
    print(f"  period      : {data.get('period')}")
    print(f"  cost_centre : {data.get('cost_centre')}   <- absent from the form")
    print(f"  lines       : {len(data.get('lines', []))}")
    for line in data.get("lines", []):
        print(f"    {line.get('date', '??'):>10}  "
              f"{str(line.get('description', ''))[:38]:38}  "
              f"{float(line.get('amount', 0)):>9.2f}")

    computed = round(sum(float(ln.get("amount", 0)) for ln in data.get("lines", [])), 2)
    stated = float(data.get("total_amount") or 0)
    print(f"\n  total_amount: {stated:.2f}  (lines sum to {computed:.2f})  "
          f"<- {'OK' if abs(stated - computed) < 0.01 else 'MISMATCH'}")


def main() -> None:
    client = bedrock_runtime()

    # A path on the command line replaces whichever sample matches its type.
    given = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    if given and not given.exists():
        sys.exit(f"{given} not found")

    if given and given.suffix.lower() == ".pdf":
        pdf = given
        part_2_pdf_as_images(client, pdf)
        return

    if given:
        part_1_image(client, given)
        return

    part_1_image(client, ensure_sample_image())

    pdf = ensure_sample_pdf()
    rendered_tokens = part_2_pdf_as_images(client, pdf)
    part_3_pdf_as_document(client, pdf, rendered_tokens)
    part_4_structured(client, pdf)


if __name__ == "__main__":
    main()